sys:1: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
R[write to console]: Error in qr.default(t(const)) : 
  NA/NaN/Inf in foreign function call (arg 1)

R[write to console]: In addition: 
R[write to console]: Warning messages:

R[write to console]: 1: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
 
R[write to console]:  library ‘/usr/share/R/library’ contains no packages

R[write to console]: 2: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
 
R[write to console]:  library ‘/usr/share/R/library’ contains no packages

Traceback (most recent call last):
  File "run_place.py", line 72, in <module>
    basis = splines.ns(np.arange(0,len(df_full.X.values)),knots=np.arange(0,len(df_full.X.values),20))
  File "/home/gcgibson/anaconda3/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 199, in __call__
    .__call__(*args, **kwargs))
  File "/home/gcgibson/anaconda3/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/home/gcgibson/anaconda3/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/home/gcgibson/anaconda3/lib/python3.7/site-packages/rpy2/rinterface.py", line 677, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in qr.default(t(const)) : 
  NA/NaN/Inf in foreign function call (arg 1)

